name: Run Pytest Tests and Generate Allure Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          cd auto
          pip install -r requirements.txt

      - name: Install Allure
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre
          curl -o allure-2.14.0.zip -L https://github.com/allure-framework/allure2/releases/download/2.14.0/allure-2.14.0.zip
          unzip allure-2.14.0.zip -d /opt
          sudo ln -s /opt/allure-2.14.0/bin/allure /usr/local/bin/allure

      - name: Run Pytest and generate allure results
        run: |
          pytest auto/test_survey.py --alluredir=allure-results

      - name: Generate Allure Report (HTML)
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
